service: wildrydes-api

plugins: 
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider: 
  name: aws
  runtime: nodejs6.10
  profile: pchinjr-cr
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions: 
  request:
    handler: request.main
    events: 
      - http:
          path: ride
          method: post
          cors: true
          authorizer: ${file(./env.json):AWS_COGNITO_POOL}
